// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ewziosmlinxqywlvegee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3emlvc21saW54cXl3bHZlZ2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODkzMjAsImV4cCI6MjA3MDE2NTMyMH0.lnBa0woIIYxqgAxzX9f1U32eeOLAplGD_8H48WX_r7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);